### ISSUE TITLE
Port components

### ISSUE THREAD

**Issue by balexand** [house-of-athlete/hoa#3]
- [x] `banner` #2
- [x] `cms_link` #8
- [x] `external_link` #8
- [x] `image_by_text` #6
- [x] `mux_video` #9
- [x] `responsive_grid` #19
- [x] `sanity_image` #16
- [x] `use_full_width_sizes` #15
- [x] `close_button` #13
- [x] `event_link` #8
- [x] `grid` #11
- [x] `image_or_video` #7
- [x] `prevent_scrolling` #14
- [x] `rich_text` #17
- [x] `social_links` #18
- [x] `video_modal` #12
